steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'
    id: 'Build JAR'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-app', '.']
    dir: '.'
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-app']
    id: 'Push Docker Image'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Retrieve the service account key from Secret Manager
        gcloud secrets versions access latest --secret="service-account-key-stock" > /workspace/service-account-key-stock.json
        gcloud auth activate-service-account --key-file=/workspace/service-account-key-stock.json
        gcloud config set project $PROJECT_ID
        gcloud run deploy spring-boot-app --image gcr.io/$PROJECT_ID/spring-boot-app --platform managed --region us-central1 --allow-unauthenticated
    id: 'Deploy to Cloud Run'

images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '120000s'
