steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: 'src'  # Ensure this points to the directory containing your pom.xml
    id: 'Build JAR'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-app', '.']
    dir: 'src'  # Ensure this points to the directory containing your Dockerfile
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-app']
    id: 'Push Docker Image'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project $PROJECT_ID
        gcloud run deploy spring-boot-app --image gcr.io/$PROJECT_ID/spring-boot-app --platform managed --region us-central1 --allow-unauthenticated
    id: 'Deploy to Cloud Run'

images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app'

logsBucket: 'gs://stocktrading-bucket'
substitutions:
  GOOGLE_APPLICATION_CREDENTIALS: 'C:\Users\10749400\Downloads\bright-lattice-442114-n2-461635b8a821.json'
timeout: '1200s'
